### ISSUE TITLE
Fehlermeldung nach Installation Contao 4.4.14

### ISSUE THREAD

**Issue by operatorone** [heimrichhannot/contao-hyphenator#2]
Nach der Installation in ein frisches Contao 4.4.14 zeigt der Browser in der Console folgende Meldung:

GET https://XXXXXX.net/system/modules/hyphenator/assets/css/hyphenator.min.css net::ERR_ABORTED

**Comment by fatcrobat** [comment]
Fixed in version `1.1.2`.

**Comment by operatorone** [comment]
Lieben Dank für den Fix.
